name: Continuous Integration
on: 
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run:  docker build --target test --tag todo-app:test .
    - run:  docker run todo-app:test
    - run:  docker build --target dependency-scan --tag todo-app:scan .
    - run:  docker run todo-app:scan
      continue-on-error: true
    
  deploy:
    name: Push to DockerHub and Trigger App Service to Deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/exercise-12' }}
    steps:
    - uses: actions/checkout@v2
    - run: echo hello deploy
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: docker build --target production --tag fletm01/todo-app:latest .
    - run: docker push fletm01/todo-app:latest
    - run: terraform init
    - run: terraform apply -auto-approve -var prefix-demo
    - run: curl -dH -X POST "$(terraform output -raw webhook_url)"